import fs from 'fs-extra';
import path from 'path';
import { runCommand } from './utils/runCommand.js';
import ora from 'ora';
import chalk from 'chalk';
import { 
  expressBoilerplate, 
  fastapiBoilerplate, 
  nestjsBoilerplate, 
  djangoBoilerplate 
} from '../templates/backend_blrp.js';
export async function createAppFromStack({ frontend, backend, database, appName ,flat}) {
  const spinner = ora(`Scaffolding ${appName}...`).start();
  const root = flat ? process.cwd() : path.resolve(process.cwd(), appName);
  const backendDir = path.join(root, 'backend');
 
  if (!flat) await fs.mkdirp(root);


  const steps = {
    nextjs: [
      `npx create-next-app@latest frontend --yes`
    ],
    react: [
      `npx create-react-app frontend`
    ],
    vue: [
      `npm create vue@latest frontend`
    ],
    svelte: [
      `npm create svelte@latest frontend`
    ],
    django: [
      `mkdir backend && cd backend && pip install django`
    ],
    express: [
      `mkdir backend && cd backend && npm init -y && npm install express`
    ],
    fastapi: [
        `mkdir backend && cd backend && echo "from fastapi import FastAPI\napp = FastAPI()" > main.py`
      ],
    nestjs: [
      `npx @nestjs/cli new backend --skip-git --skip-install`
    ],
    nestjs: [
        `npx @nestjs/cli new backend --skip-git --skip-install`
      ],
      mongodb: [
        `echo "// MongoDB config placeholder" > backend/mongo.js`
      ],
      postgresql: [
        `echo "// PostgreSQL config placeholder" > backend/postgres.js`
      ],

      mysql: [
        `echo "// MySQL config placeholder" > backend/mysql.js`
      ],

      firebase: [
        `echo "// Firebase config placeholder" > backend/firebase.js`
      ],
  };

  const allCommands = [
    ...(steps[frontend] || []),
    ...(steps[backend] || []),
    ...(steps[database] || []),
  ];

  try {
    for (const cmd of allCommands) {
      spinner.text = `Running: ${cmd}`;
      await runCommand(cmd, { cwd: root });
    }



spinner.text = `Creating backend boilerplate...`;
if (backend === 'express') {
  await fs.ensureDir(backendDir);
  await fs.writeFile(path.join(backendDir, 'index.js'), expressBoilerplate);
}

if (backend === 'fastapi') {
  await fs.ensureDir(backendDir);
  await fs.writeFile(path.join(backendDir, 'main.py'), fastapiBoilerplate);
}

if (backend === 'nestjs') {
  await fs.ensureDir(backendDir);
  await fs.writeFile(path.join(backendDir, 'src/app.controller.ts'), nestjsBoilerplate);
}

if (backend === 'django') {
  await fs.ensureDir(backendDir);
  await fs.writeFile(path.join(backendDir, 'views.py'), djangoBoilerplate);
}


    await fs.writeFile(path.join(root, 'README.md'), `# ${appName}\n\nGenerated by boilrplate.`);

    spinner.succeed(`✅ ${appName} scaffolded!`);
    console.log(chalk.green(`\nNext steps:`));
    console.log(chalk.cyan(`cd ${appName} && code .`));
  } catch (err) {
    spinner.fail('Scaffolding failed.');
    console.error(chalk.red(err.message));
  }
}
